import os

ACCESS_TOKEN_KEY = os.getenv("ACCESS_TOKEN_KEY")
REQUEST_ID_KEY = os.getenv("REQUEST_ID_KEY")
REQUEST_TIME_KEY = os.getenv("REQUEST_TIME_KEY")
CREDENTIALS_URL = os.getenv("CREDENTIALS_URL")